### PR TITLE
Tokenizer (issue #3)

### PR DESCRIPTION
**Pull request by jamaliki**

### CODE REVIEW

**Review by Muedi — COMMENTED** [review]
Looks very cool! 
If you have the time, would youy mind commenting the rust and python code a bit more? I'd like to get to know what is going on here as I hadn't have the chance to work with tokenizers yet. 
If thats too much work for your current schedule no problem of course! :)

**Comment by jamaliki** [comment]
That's a good point about the commenting @Muedi, I'll do it the moment I have a chance!

**Comment by jamaliki** [comment]
Hey @Muedi I added some comments to the rust code. I think the python is pretty simple, but if you have ideas of where I should add more explanations, I'm happy to do so. Please let me know if you think anything would be unclear for others.

**Review by Muedi — APPROVED** [review]
Thanks, very comprehensive! 
I'll try to use this with the protgym script, then i'll get back to you if I think the py script also needs comments or some explaination :)

**Comment by pascalnotin** [comment]
Should we subclass the tokenizer class in tokenizer.py with an "AptTokenizer" that includes the points we made today (eg., collapsing X and <UNK>). What is the role of <null_1>? Do we need "." and "-"? maybe if we use alignments?

**Comment by jamaliki** [comment]
How's this?

**Review by pascalnotin — COMMENTED** [review]
Looks good!

**Pull request merged**
