### PR TITLE
Clean up modeling code (with rotary embedding added)

### PR DESCRIPTION
**Pull request by talkhanz**
modeling task with rotary embedding. I have added the APTAttention,APTBlock and APTMLP which is a bit more concise than our current code. 

Meanwhile, i'll push a PR for alibi encoding separately so we could decouple the code.

@pascalnotin @jamaliki

### CODE REVIEW

**Comment by othertea** [comment]
Hey @talkhanz, thanks for creating this PR! It looks good to me, just one small request -- do you think you could change the PR title to make it a bit more descriptive? 
Just as an example, something like "Clean up modeling code" (if you think this is an appropriate description) but of course it's up to you!

**Comment by talkhanz** [comment]
> Hey @talkhanz, thanks for creating this PR! It looks good to me, just one small request -- do you think you could change the PR title to make it a bit more descriptive? Just as an example, something like "Clean up modeling code" (if you think this is an appropriate description) but of course it's up to you!

yes, i'll make it a bit more descriptive. Thanks for the feedback!

**Review by othertea — APPROVED** [review]
Looks good to me, thanks @talkhanz !

**Comment by talkhanz** [comment]
welcome!

> Looks good to me, thanks @talkhanz !

Thanks for merging @othertea !

**Pull request merged**
