### PR TITLE
Fix issue with add_special_tokens and return_tensors

### PR DESCRIPTION
**Pull request by jamaliki**

### CODE REVIEW

**Comment by jamaliki** [comment]
Hey @talkhan take a look to see if this branch fixed your issue, if it does LMK and I will merge.

**Comment by pascalnotin** [comment]
This [line](https://github.com/OpenBioML/protein-lm-scaling/pull/17/files#diff-821fd209f9ef1401aa279977ebcfe35a6a4c2ce5c6fc37070257a8dadff30f18R54) will throw an error if max_sequence_length is None and return_tensors is False

**Comment by talkhanz** [comment]
@jamaliki yes this is working fine for me. Thanks for the fix!

**Comment by jamaliki** [comment]
@pascalnotin I'm going to add a proper test so that all combinations of kwargs work

**Comment by jamaliki** [comment]
@pascalnotin how does it look now?

**Comment by othertea** [comment]
@jamaliki Sorry, doesn't the problem @pascalnotin referred to still exist? If `max_sequence_length` is `None` and `return_tensors` is `False`, `max_sequence_length` will still be `None` by the time it reaches https://github.com/OpenBioML/protein-lm-scaling/blob/3fc529535efbd9fde93c1786af184fc65de85785/protein_lm/tokenizer/tokenizer.py#L54
at which point, it will throw a TypeError.

(Also nit: type hint on https://github.com/OpenBioML/protein-lm-scaling/blob/3fc529535efbd9fde93c1786af184fc65de85785/protein_lm/tokenizer/tokenizer.py#L48 should be `Optional[int]`)

**Comment by jamaliki** [comment]
Hi @othertea, good call on the type hint, fixed that. 

I added more tests, but I don't think you are quite correct on the `max_sequence_length` because right above it we make sure that it is not `None`

**Comment by othertea** [comment]
@jamaliki Hmm... what I see above that line applies only if `max_sequence_length` is `None` _and_ `return_tensors` is `True` and will be skipped if `return_tensors` is `False`.
https://github.com/OpenBioML/protein-lm-scaling/blob/b7ff61b71f7087b0d37b916d88170ec169b9f211/protein_lm/tokenizer/tokenizer.py#L51-L54

I also just checked running the tests (thanks for adding them, by the way!) and I get four failing ones,  2 of them because of this problem. Trying figure out what I'm missing here...

**Comment by jamaliki** [comment]
@othertea sorry, this was a bug that was introduced in the merge conflict. That line should not be there since I added the line below it.

**Comment by othertea** [comment]
Ah, that explains it! Thank you for fixing.

**Comment by jamaliki** [comment]
@othertea if it is ok with you, could you approve and we can merge

**Review by othertea — APPROVED** [review]
LGTM!

**Pull request merged**
